#!/bin/sh

if [ $1 = power_supply ]; then
    if [ x"$ACTION" = x"change" -a x"$POWER_SUPPLY_NAME" = x"usb" ]; then
        if [ $POWER_SUPPLY_ONLINE -eq 1 ]; then
            autosuspend prevent
        else
            autosuspend okay
        fi
    fi
fi

