#!/bin/sh

if [ $1 = power_supply ]; then
    type=`cat /sys$DEVPATH/type`
    if [ x"$ACTION" = x"change" -a x"$type" = x"USB" ]; then
        if [ $POWER_SUPPLY_ONLINE -eq 1 ]; then
            autosuspend lock usb-connected
        else
            autosuspend unlock usb-connected
        fi
    fi
fi

