#!/bin/sh

if [ -z $ACTION ] || [ $ACTION = "add" ] ; then
    if [ -e /var/lib/usbwatcher/state ]; then
        . /var/lib/usbwatcher/state
        if [ x"$STATE" = x"mass_storage" ]; then
            exit 0;
        fi
    fi

    for i in /dev/mmcblk*
    do
        D1=`echo $i | sed -e s/p[0-9]*//`
        D2="/dev/"`echo $MDEV | sed -e s/p[0-9]*//`
        if [ $D1 != $D2 ]
        then
            umount $i
            rm -f $i
        fi
    done

    mount -o iocharset=utf8,flush,noatime /dev/$MDEV /media/sd || mount -o noatime /dev/$MDEV /media/sd

    killall -HUP madshelf
    exit 0
fi

if [ $ACTION = "remove" ] ; then
    umount -fl /dev/$MDEV
    killall -HUP madshelf
    exit 0
fi

echo "Unknown action. This script must be called by mdev!"
exit 1
